name: build docker image

on:
  push:
    branches: master

  workflow_run:
    workflows: ["trigger"]
    types: [completed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          LATEST=$(wget -q -O - "https://api.github.com/repos/muldjord/skyscraper/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          docker buildx build --push \
          --build-arg SKYSCRAPER_RELEASE=${LATEST} \
          --cache-from mellotanica/skyscraper:latest \
          --tag mellotanica/skyscraper:latest \
          --tag mellotanica/skyscraper:${LATEST} \
          --platform linux/amd64,linux/armhf,linux/arm64 .
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: mellotanica/skyscraper

